### ISSUE TITLE
Getting rid of git submodules to ease migration to conda-forge

### ISSUE THREAD

**Issue by hbredin** [Yaafe/Yaafe#41]
I am currently trying to prepare a `conda-forge` release of Yaafe.

`conda-forge` recommends to link to a source archive instead of Github repository.
One way of doing it is to directly link to Yaafe releases in `meta.yaml` file:

```yaml
source:
  fn: yaafe-0.70-rc1.tar.gz
  url: https://github.com/Yaafe/Yaafe/archive/0.70-rc1.tar.gz
```

Unfortunately, this `tar.gz` file does not contain the code of `externals` git submodules `eigen` and `fmemopen`. 

Is there a (legal? technical?) reason not to directly copy `eigen` and `fmemopen` source code in `externals` directory? This would make the `conda-forge` migration seamless...
